import React, { Component } from "react"

import ClientForm from "./components/ClientForm"

class App extends Component {
  constructor() {
    super()
    this.state = {
      client: {
        name: {
          last: "",
          first: ""
        },
        address: {
          number: "",
          street: "",
          town: "",
          zip: ""
        },
        usageData: Array(12).fill(0),
        sRECMarketSector: 1,
        isCommercial: true,
        incentivePrograms: {
          fITC: true,
          sMART: false,
          sREC: true,
          mACRS: true,
          nantucketSolar: false,
          netMetering: true
        },
        taxRate: 0.35
      },
      system: {
        arrays: [
          {
            moduleAmount: 120,
            moduleCapacity: 310,
            tilt: 45,
            azimuth: 156,
            arrayType: 1,
            costPerWatt: 0,
            losses: 14,
            // Output will be generated by PVWatts fetch
            output: []
          }
        ],
        defaultSettings: {
          moduleType: 1,
          // This is data from Boston TMY2
          lat: 41.68,
          lon: -69.96
        },
        hasError: true,
        hasSubmitted: false,
        totalSystemCost: 0
      }
    }
  }

  render() {
    return <ClientForm {...this.state.client} />
  }
}

export default App
